### PR TITLE
Allow rotations from 0-360

### PR DESCRIPTION
**Pull request by 61352151511**
Removes the buttons for rotating by 90° and adds a slider beside the scale one for a rotation from 0° to 360°

I don't know how to save GIFs using java, however perhaps this could be looked into and then there could be a button to create a GIF of the entity/block doing one complete spin?

preview

### CODE REVIEW

**Comment by herbix** [comment]
Good idea.
But could you keep the old rotation buttons so that one can precisely set rotation to multiples of 90?

**Comment by 61352151511** [comment]
Adding that button made me want to reposition every other button because I couldn't find somewhere for it to go, but I think it looks fine. Let me know what you think :smile: 

preview2

**Comment by herbix** [comment]
Well... "Done" button makes me uncomfortable. I think bottom of "Done" and right bottoms should be aligned. Repositioning buttons may be a hard work. But I'm sure you could do it. :blush:

**Comment by 61352151511** [comment]
Well the thing is, there's practically no room, unless all the sliders and other buttons are moved up, which will take room from the rendering area itself. I didn't quite understand "I think bottom of "Done" and right bottoms should be aligned." so if you could just edit the image in paint and drag the done button to where you want it to be, I'll see what I can do

**Comment by herbix** [comment]
Well. Since it may cost much time to explain, I would do it by myself.

**Comment by herbix** [comment]
And this is the result.

**Comment by 61352151511** [comment]
Nicely done, I guess you scratched image size then?

Sent from Samsung MobileChaofan Yang notifications@github.com wrote:

And this is the result.

---

**Comment by herbix** [comment]
Yes, I moved down the buttons and expanded the center canvas.

**Pull request merged**
